webcamp-commit-crayon/nagano_cake2

app/controllers/admins/confirmations_controller.rb
app/controllers/application_controller.rb
app/views/admin/homes/top.html.erb
app/views/admin/items/_header.html.erb
app/views/admin/items/index.html.erb
app/views/admins/sessions/new.html.erb

アプリケーションコントローラ　ログイン後のリダイレクト先指定しました。

[Addログイン先指定]

---

app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
db/migrate/20210718042450_add_from_tocustomers.rb
db/schema.rb

新規登録、ログイン画面調整

---

app/controllers/public/items_controller.rb
app/models/item.rb
config/routes.rb

・ルーティング内にpublicメソッド追加してitems,cartitemsなどをメソッド内に移動

publicルーティング調整

---

app/views/public/homes/_header.html.erb

headerミス変更

---

app/controllers/application_controller.rb
app/views/public/homes/_header.html.erb

・会員新規登録、ログイン機能調整
・headerのリンクの誤表記修正

会員新規登録、ログイン機能修正

---

app/controllers/application_controller.rb
app/controllers/public/items_controller.rb
app/views/public/items/index.html.erb

・新規登録保存の機能修正
　（アプリケーションコントローラーにbefore_actionなど追加）
・商品一覧レイアウト構築（途中）

[fix]新規登録保存機能修正+α

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/index.html.erb
app/views/admin/customers/show.html.erb

[修正]会員一覧、会員詳細、会員編集

---

app/controllers/admin/genres_controller.rb

[ジャンルコントローラー変更]

---

app/controllers/admin/genres_controller.rb
app/views/admin/items/new.html.erb

[修正]商品登録画面のステータス修正

---

app/controllers/public/customers_controller.rb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb

会員側のeditページ作成
会員側のupdate機能作成完了

editupdate追加

---

app/assets/stylesheets/admin/items.scss
app/views/admin/genres/edit.html.erb
app/views/admin/items/new.html.erb

[管理者側商品新規登録viewの変更]

---

app/views/admin/items/index.html.erb
app/views/admin/items/show.html.erb
app/views/public/items/index.html.erb

[修正]管理者側/商品価格の小数点

---

app/assets/stylesheets/application.scss
app/controllers/admin/genres_controller.rb
app/views/public/items/index.html.erb

[修正]会員側商品一覧のレイアウト調整

---

app/controllers/public/addresses_controller.rb
app/views/public/addresses/index.html.erb

addressesのedit機能追加
削除機能追加
編集ページ追加

addresses完成

---

app/views/public/addresses/edit.html.erb
app/views/public/addresses/index.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb

[修正]配送先一覧のレイアウト

---

app/controllers/cart_items_controller.rb
app/controllers/public/cart_items_controller.rb
app/controllers/public/items_controller.rb
app/models/cart_item.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/show.html.erb

商品詳細画面
・数量指定機能追加
・カートへ進むボタン変更
カート機能
・入れた商品の一覧追加
・商品の数量変更機能追加
・商品の削除機能追加
・top画面移動する買い物続けるボタン追加
・カートを空にするボタン追加
・情報入力（Orders）に進むボタン追加

[update]商品詳細個数指定、カート機能追加

---

app/controllers/public/cart_items_controller.rb

・数量変更機能修正（find_by→find)
・削除機能修正　　（find_by→find)
その他変数修正

[fix]カート機能修正

---

app/assets/javascripts/searches.coffee
app/assets/stylesheets/searches.scss
app/controllers/searches_controller.rb
app/helpers/searches_helper.rb
app/models/customer.rb
app/models/item.rb
app/views/admin/homes/_header.html.erb
app/views/layouts/_search.html.erb
app/views/public/homes/_header.html.erb
app/views/public/items/_index.html.erb
app/views/searches/search.html.erb
config/routes.rb
test/controllers/searches_controller_test.rb

[追加]商品名の検索機能

---

app/models/item.rb
app/views/admins/sessions/new.html.erb

[バリデーション、管理者レイアウト変更]

---

app/views/public/cart_items/index.html.erb

[fix]注文に進むボタン名変更

---

app/controllers/public/orders_controller.rb
app/views/public/addresses/edit.html.erb
app/views/public/addresses/index.html.erb
app/views/public/orders/comfirm.html.erb
app/views/public/orders/complete.hrml.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb
config/routes.rb

orderのshow,new,index,complete,comfirmの機能、ページ追加しました。

orderの機能追加

---

app/assets/stylesheets/admin/items.scss
app/views/admin/items/show.html.erb

[管理者画像投稿サイズ変更]

---

app/controllers/admin/homes_controller.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/show.html.erb
app/views/admin/homes/top.html.erb

[管理者側view調整]

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/items_controller.rb
app/models/cart_item.rb
app/models/item.rb
app/views/public/items/show.html.erb

[fix]商品詳細画面　個数空入力不可設定追加

---

app/controllers/admin/genres_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/public/addresses_controller.rb
app/controllers/public/orders_controller.rb
app/models/address.rb
app/views/admin/orders/index.html.erb
app/views/public/addresses/_flash.html.erb
app/views/public/addresses/index.html.erb
config/routes.rb

[追加]配送先バリデーション

---

Gemfile
Gemfile.lock
app/controllers/public/orders_controller.rb
app/views/public/orders/comfirm.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb
config/application.rb
config/routes.rb

order途中経過2

---

app/controllers/public/orders_controller.rb

ordercontroller修正

---

app/controllers/admin/order_details_controller.rb
app/controllers/admin/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/homes/top.html.erb
app/views/admin/orders/show.html.erb

[追加]管理者側/注文一覧＆注文詳細（途中）

---

app/controllers/admin/orders_controller.rb
app/models/order_detail.rb
app/views/admin/orders/show.html.erb
config/routes.rb

[追加]管理者側/注文履歴詳細（途中）

---

app/controllers/admin/order_details_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/public/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/orders/show.html.erb
app/views/public/orders/show.html.erb
db/migrate/20210717081316_create_order_details.rb
db/migrate/20210717084724_create_orders.rb
db/schema.rb

[追加]制作ステータスと注文ステータスの自動更新

---

app/controllers/admin/items_controller.rb
app/controllers/admins/sessions_controller.rb

[ログアウトした後のリダイレクト先変更]

---

app/views/admin/genres/index.html.erb

[修正]ジャンル登録

---

app/assets/stylesheets/admin/customers.scss
app/views/admin/customers/edit.html.erb
app/views/admin/customers/show.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/show.html.erb

[修正]管理者側/会員編集ボタン

---

app/controllers/admin/homes_controller.rb
app/views/admin/customers/show.html.erb

[修正]管理者側の会員別注文履歴一覧
